#############################################################################################################################
## Automation Title - Laundry: Washer Reminder
## Use Case - Use this automation to send a reminder after an NFC tap to all devices in notify
## This automation will wait 30 minutes and send the actionable notification. Hitting the button "Flipped Laundry"
## will clear the notification for all devices automatically. This should work on iPhone and Android but of course requires
## the home assistant companion app.
#############################################################################################################################


alias: "Laundry: Washer Reminder"
description: ""
trigger:
  - platform: tag
    tag_id: XXXXX-XXXXXX-XXXXXX-XXXXXX
condition: []
action:
  - service: notify.notify
    data:
      message: Flip over the tester
      title: Laundry
      data:
        priority: high
        tag: laundry_notification
        actions:
          - action: CLEAR_LAUNDRY
            title: Flipped Laundry
  - wait_for_trigger:
      platform: event
      event_type: mobile_app_notification_action
      event_data:
        action: CLEAR_LAUNDRY
    continue_on_timeout: true
  - service: notify.notify
    data:
      message: clear_notification
      data:
        tag: laundry_notification
mode: single
