alias: Pill - Reset Boolean
description: ""
trigger:
  - platform: time
    at: "00:05:00"
condition: []
action:
  - service: input_boolean.turn_off
    data: {}
    target:
      entity_id: input_boolean.pill
mode: single
