#Runs at 12:05 AM and resets the boolean, I'm sure there is a better way but this is the way I am resetting the boolean for now

alias: Pill - Reset Boolean
description: ""
trigger:
  - platform: time
    at: "00:05:00"
condition: []
action:
  - service: input_boolean.turn_off
    data: {}
    target:
      entity_id: input_boolean.pill
mode: single
